product-name = "tauri-superapp"
version = "0.1.0"
identifier = "com.tauri-superapp.app"

[build]
frontend-dist = "../dist"

[bundle]
active = false
targets = "all"
icon = [
    "icons/32x32.png",
    "icons/128x128.png",
    "icons/128x128@2x.png",
    "icons/icon.icns",
    "icons/icon.ico"
]

[app]
with-global-tauri = true

[[app.windows]]
title = "tauri-superapp"
width = 800
height = 600
