[package]
name = "wapp_a"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
console_error_panic_hook = { workspace = true }
console_log = { workspace = true }
leptos = { workspace = true }
log = { workspace = true }
